# version: '3'
# services:
#   webserver:
#     build:
#       dockerfile: requirements/nginx/Dockerfile
#     image: nginx:alpine
#     container_name: nginx
#     restart: always
#     ports:
#       - 80:80
      # - 443:443
    # volumes:
    #   - ./requirements/nginx/conf:etc/nginx/conf.d:ro
# version: "3.9"
# services:
#   nginx:
#     build: requirements/nginx/
#     # image: nginx:latest
#     container_name: nginx
#     restart: always
#     ports:
#     - 80:80
#     - 443:443
    # expose:
    #   - 443
    # volumes:
    # - ./requirements/nginx/conf/nginx.conf:/etc/nginx/nginx.conf
    # - ./requirements/nginx/conf/ssl:/ssl/
    # environment:
    # - NGINX_HOST=eassouli.42.fr
    # - NGINX_PORT=80
    # env_file:
      # - .env

version: "3.9"
services:
  database:
    container_name: database
    build: requirements/mariadb
    entrypoint: /entrypoint.sh
    restart: always
    ports:
      - 3306:3306
    volumes:
      - database:/var/lib/mysql
    networks:
      - vpcbr
    env_file:
      - .env

  wordpress:
    container_name: wordpress
    depends_on:
      - database
    build: requirements/wordpress
    entrypoint: /entrypoint.sh
    restart: always
    volumes:
      - wordpress_data:/var/www/html
    ports:
     - 9000:9000
    networks:
      - vpcbr
    env_file:
      - .env
    # secrets:

  nginx:
    container_name: nginx
    depends_on:
      - wordpress
    build: requirements/nginx/
    entrypoint: /entrypoint.sh
    restart: always
    volumes:
      - ./requirements/nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - wordpress_data:/var/www/html
    ports:
      - 80:80
      - 443:443
    # networks:
    #   - custom-driver-1
    env_file:
      - .env

volumes:
  database:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/eithan/data/database
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/eithan/data/wordpress

networks:
  vpcbr:
    driver: bridge