# version: '3'
# services:
#   webserver:
#     build:
#       dockerfile: requirements/nginx/Dockerfile
#     image: nginx:alpine
#     container_name: nginx
#     restart: always
#     ports:
#       - 80:80
      # - 443:443
    # volumes:
    #   - ./requirements/nginx/conf:etc/nginx/conf.d:ro
# version: "3.9"
# services:
#   nginx:
#     build: requirements/nginx/
#     # image: nginx:latest
#     container_name: nginx
#     restart: always
#     ports:
#     - 80:80
#     - 443:443
    # expose:
    #   - 443
    # volumes:
    # - ./requirements/nginx/conf/nginx.conf:/etc/nginx/nginx.conf
    # - ./requirements/nginx/conf/ssl:/ssl/
    # environment:
    # - NGINX_HOST=eassouli.42.fr
    # - NGINX_PORT=80
    # env_file:
      # - .env

version: "3.9"
services:
  database:
    build: requirements/mariadb
    container_name: database
    restart: always
    ports:
      - 3306:3306
    volumes:
      - database:/var/lib/mysql
      # - ./requirements/mariadb/conf/setup.sql:/setup.sql
    # networks:
    #   - back
    env_file:
      - .env
  nginx:
    build: requirements/nginx/
    container_name: nginx
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./requirements/nginx/conf/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - front
      - back
    env_file:
      - .env

volumes:
  database:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/eithan/data/database
  # wordpress-data:
  #   driver: local
  #   driver_opts:
  #     type: none
  #     o: bind
  #     device: /home/eithan/data/wordpress

networks:
  front:
    driver: bridge
  back:
    driver: bridge