# version: '3'
# services:
#   webserver:
#     build:
#       dockerfile: requirements/nginx/Dockerfile
#     image: nginx:alpine
#     container_name: nginx
#     restart: always
#     ports:
#       - 80:80
      # - 443:443
    # volumes:
    #   - ./requirements/nginx/conf:etc/nginx/conf.d:ro
version: '3.9'
services:
  web:
    build: requirements/nginx/
    # image: nginx:latest
    container_name: nginx
    restart: always
    ports:
    - 443:443
    # expose:
    #   - 443
    # volumes:
    # - ./requirements/nginx/conf/nginx.conf:/etc/nginx/nginx.conf
    # - ./requirements/nginx/conf/ssl:/ssl/
    # environment:
    # - NGINX_HOST=eassouli.42.fr
    # - NGINX_PORT=80
    env_file:
      - .env