# version: '3'
# services:
#   webserver:
#     build:
#       dockerfile: requirements/nginx/Dockerfile
#     image: nginx:alpine
#     container_name: nginx
#     restart: always
#     ports:
#       - 80:80
      # - 443:443
    # volumes:
    #   - ./requirements/nginx/conf:etc/nginx/conf.d:ro
web:
  image: nginx:alpine
  container_name: nginx
  restart: always
  volumes:
   - ./requirements/nginx/templates:/etc/nginx/templates
  ports:
   - "8080:80"
  environment:
   - NGINX_HOST=eassouli.42.fr
   - NGINX_PORT=80