version: "3.9"
services:
  mariadb:
    container_name: mariadb
    image: mariadb
    build: requirements/mariadb
    entrypoint: /entrypoint.sh
    restart: on-failure
    volumes:
      - database:/var/lib/mysql
    networks:
      - inception
    env_file:
      - .env

  wordpress:
    container_name: wordpress
    depends_on:
      - mariadb
    image: wordpress
    build: requirements/wordpress
    entrypoint: /entrypoint.sh
    restart: on-failure
    volumes:
      - wordpress_db:/var/www/wordpress
    networks:
      - inception
    env_file:
      - .env

  nginx:
    container_name: nginx
    depends_on:
      - wordpress
    image: nginx
    build: requirements/nginx/
    entrypoint: /entrypoint.sh
    restart: on-failure
    volumes:
      # - ./requirements/nginx/conf/wordpress.conf:/etc/nginx/conf.d/wordpress.conf
      - wordpress_db:/var/www/wordpress
    ports:
      - 443:443
    networks:
      - inception
    env_file:
      - .env

volumes:
  database:
    name: database
    driver: local
    driver_opts:
      type: volume
      o: bind
      device: /home/eithan/data/database
  wordpress_db:
    name: wordpress_db
    driver: local
    driver_opts:
      type: volume
      o: bind
      device: /home/eithan/data/wordpress_db

networks:
  inception: