FROM alpine:3.14

LABEL maintainer="eassouli <eassouli@student.42.fr>"

# INSTALLING DEPENDANCIES
RUN apk update && apk add mariadb openrc

# MYSQL SETUP
RUN sed -i "s/999/99/" /etc/group
RUN deluser mysql
RUN adduser -u 999 mysql -D
RUN mkdir -p /data/mysql
RUN chown -R mysql:mysql /data/mysql

# MARIADB SETUP
RUN mkdir -p /run/openrc
RUN touch /run/openrc/softlevel
RUN /etc/init.d/mariadb setup
# RUN mysql_install_db --user=mysql

# COPY FILES
# COPY ./conf/* /etc/mysql

# VOLUMES
# VOLUME /var/lib/mysql

# EXPOSING PORTS
EXPOSE 3306

# DAEMON
ENTRYPOINT ["mysqld_safe"]